import 'package:flutter/material.dart';
import '../../../core/constants/gym_images.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_text_styles.dart';
import '../../../core/utils/responsive.dart';
import '../../../core/widgets/reveal_on_scroll.dart';

class AboutSection extends StatelessWidget {
  const AboutSection({super.key});

  static const _pillars = [
    ('Coached, not just open.', 'Every floor has a coach on it during peak hours — not just a rack of equipment and good luck.'),
    ('Programmed, not random.', 'Your session is written by someone tracking your last four weeks, not generated by an app guessing at your level.'),
    ('Built for the long run.', 'No 6am-only access, no 90-day contracts. A floor you can actually keep showing up to.'),
  ];

  @override
  Widget build(BuildContext context) {
    final isDesktop = Responsive.isDesktop(context);
    final gutter = Responsive.gutter(context);

    final image = ClipRect(
      child: AspectRatio(
        aspectRatio: isDesktop ? 4 / 5 : 16 / 10,
        child: Image.network(
          GymImages.interiorWide,
          fit: BoxFit.cover,
          errorBuilder: (context, error, stack) => Container(color: AppColors.surface),
        ),
      ),
    );

    final copy = Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('ABOUT STRONGHOLD', style: AppTextStyles.eyebrow()),
        const SizedBox(height: 16),
        Text(
          'A gym built around\none good habit.',
          style: AppTextStyles.headline(size: isDesktop ? 44 : 34),
        ),
        const SizedBox(height: 20),
        Text(
          'STRONGHOLD opened on Peponi Road in 2020 with one floor, two coaches, '
          'and a bet that Nairobi wanted a gym that coached people rather than just '
          'housed equipment. Six years on, that\'s still the whole model.',
          style: AppTextStyles.body(size: 16),
        ),
        const SizedBox(height: 32),
        for (final p in _pillars) ...[
          _Pillar(title: p.$1, body: p.$2),
          const SizedBox(height: 22),
        ],
      ],
    );

    return RevealOnScroll(
      child: Container(
        color: AppColors.concrete,
        padding: EdgeInsets.symmetric(horizontal: gutter, vertical: isDesktop ? 100 : 64),
        child: isDesktop
            ? Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  Expanded(flex: 5, child: image),
                  const SizedBox(width: 72),
                  Expanded(flex: 6, child: copy),
                ],
              )
            : Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  image,
                  const SizedBox(height: 40),
                  copy,
                ],
              ),
      ),
    );
  }
}

class _Pillar extends StatelessWidget {
  const _Pillar({required this.title, required this.body});
  final String title;
  final String body;

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          width: 3,
          height: 42,
          margin: const EdgeInsets.only(top: 4),
          color: AppColors.caution,
        ),
        const SizedBox(width: 16),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(title, style: AppTextStyles.bodyStrong(size: 17)),
              const SizedBox(height: 4),
              Text(body, style: AppTextStyles.body(size: 14.5)),
            ],
          ),
        ),
      ],
    );
  }
}
